### ISSUE TITLE
RDFizer: LIDO bug

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#106]
@agazzarini 

I do not know what you have changed last week but now the LIDO mapping does not work.
I found the following error in "infraestructure.log" file:
```
2015-05-11 15:16:33,728 ERROR Failed delivery for (MessageId: ID-aliada-scanbit-50383-1431347914974-0-45 on ExchangeId: ID-aliada-scanbit-50383-1431347914974-0-90). Exhausted after delivery attempt: 1 caught: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'one' in  class eu.aliada.rdfizer.pipeline.format.xml.OXPath threw exception java.lang.ClassCastException: java.lang.String cannot be cast to org.w3c.dom.NodeList at VM_global_library.vm[line 55, column 21]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route13           ] [route13           ] [seda://lido-record-channel?blockWhenFull=true&concurrentConsumers=2&size=1000 ] [       878]
[route6            ] [to7               ] [seda:lido-record-channel?concurrentConsumers=2&size=1000&blockWhenFull=true   ] [         0]
[route13           ] [process31         ] [ref:string-to-xml                                                             ] [         1]
[route13           ] [process32         ] [ref:xml-to-rdf                                                                ] [        10]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-aliada-scanbit-50383-1431347914974-0-90
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID-aliada-scanbit-50383-1431347914974-0-45, CamelFileAbsolute=true, CamelFileAbsolutePath=/work/data/aliada/lido/.working/mfa_lido_20_presentation_en1431350153204.xml.477, CamelFileLastModified=1431350126000, CamelFileLength=245031, CamelFileName=mfa_lido_20_presentation_en1431350153204.xml.477, CamelFileNameConsumed=mfa_lido_20_presentation_en1431350153204.xml.477, CamelFileNameOnly=mfa_lido_20_presentation_en1431350153204.xml.477, CamelFileParent=/work/data/aliada/lido/.working, CamelFilePath=/work/data/aliada/lido/.working/mfa_lido_20_presentation_en1431350153204.xml.477, CamelFileRelativePath=/work/data/aliada/lido/.working/mfa_lido_20_presentation_en1431350153204.xml.477, CamelRedelivered=false, CamelRedeliveryCounter=0, format=lido, jobId=477}
	BodyType            org.apache.xerces.dom.DeferredDocumentImpl
	Body                <lido:lido>    <lido:lidoRecID lido:source="SzÃ©pmÅ±vÃ©szeti MÃºzeum" lido:type="local">szepmuveszeti.hu_object_440</lido:lidoRecID>    <lido:category>      <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00096</lido:conceptID>      <lido:conceptID lido:type="URI">http://www.cidoc-crm.org/crm-concepts/E22</lido:conceptID>      <lido:term xml:lang="en">man-made object</lido:term>    </lido:category>    <lido:descriptiveMetadata xml:lang="en">      <lido:objectClassificationWrap>        <lido:objectWorkTypeWrap>          <lido:objectWorkType lido:sortorder="1" lido:type="local">            <lido:term lido:encodinganalog="classification_mapped" lido:label="classification">paintings</lido:term>          </lido:objectWorkType>        </lido:objectWorkTypeWrap>        <lido:classificationWrap>          <lido:classification lido:type="europeana:type">            <lido:term>IMAGE</lido:term>          </lido:classification>          <lido:classification lido:sortorder="3" lido:type="Collection name">            <lido:term lido:encodinganalog="department_orig" lido:label="collection">Department of Art after 1800</lido:term>          </lido:classification>        </lido:classificationWrap>      </lido:objectClassificationWrap>      <lido:objectIdentificationWrap>        <lido:titleWrap>          <lido:titleSet lido:sortorder="1">            <lido:appellationValue lido:label="title" lido:pref="preferred" xml:lang="en">Mary Magdalene</lido:appellationValue>          </lido:titleSet>        </lido:titleWrap>        <lido:repositoryWrap>          <lido:repositorySet lido:type="Current">            <lido:repositoryName>              <lido:legalBodyName>                <lido:appellationValue lido:pref="preferred" xml:lang="hu">SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:appellationValue>              </lido:legalBodyName>              <lido:legalBodyWeblink lido:formatResource="text/html" lido:label="homepage" xml:lang="en">http://www.szepmuveszeti.hu</lido:legalBodyWeblink>            </lido:repositoryName>            <lido:workID lido:sortorder="1" lido:type="Inventory Number">389.B</lido:workID>            <lido:repositoryLocation>              <lido:namePlaceSet>                <lido:appellationValue lido:pref="preferred" xml:lang="hu">1146 Budapest, DÃ³zsa GyÃ¶rgy Ãºt 41.</lido:appellationValue>              </lido:namePlaceSet>              <lido:gml>                <gml:Point xmlns:gml="http://www.opengis.net/gml" srsName="EPSG-4326">                  <gml:pos>47.516353 19.076471</gml:pos>                </gml:Point>              </lido:gml>              <lido:partOfPlace lido:politicalEntity="City">                <lido:placeID lido:label="GeoNames identifier" lido:source="GeoNames" lido:type="URI">http://sws.geonames.org/3054643</lido:placeID>                <lido:namePlaceSet>                  <lido:appellationValue lido:pref="preferred" xml:lang="en">Budapest</lido:appellationValue>                </lido:namePlaceSet>              </lido:partOfPlace>              <lido:partOfPlace lido:politicalEntity="Country">                <lido:placeID lido:label="GeoNames identifier" lido:source="GeoNames" lido:type="URI">http://sws.geonames.org/719819</lido:placeID>                <lido:namePlaceSet>                  <lido:appellationValue lido:pref="preferred" xml:lang="en">Hungary</lido:appellationValue>                </lido:namePlaceSet>              </lido:partOfPlace>              <lido:partOfPlace lido:politicalEntity="Continent">                <lido:placeID lido:label="GeoNames identifier" lido:source="GeoNames" lido:type="URI">http://sws.geonames.org/6255148</lido:placeID>                <lido:namePlaceSet>                  <lido:appellationValue lido:pref="preferred" xml:lang="en">Europe</lido:appellationValue>                </lido:namePlaceSet>              </lido:partOfPlace>            </lido:repositoryLocation>          </lido:repositorySet>        </lido:repositoryWrap>        <lido:objectMeasurementsWrap>          <lido:objectMeasurementsSet lido:sortorder="1">            <lido:displayObjectMeasurements>116,5 x 89,5 cm</lido:displayObjectMeasurements>            <lido:objectMeasurements>              <lido:measurementsSet lido:sortorder="1">                <lido:measurementType lido:encodinganalog="dimension_type">height</lido:measurementType>                <lido:measurementUnit lido:encodinganalog="dimension_unit">centimeters</lido:measurementUnit>                <lido:measurementValue>116.5</lido:measurementValue>              </lido:measurementsSet>              <lido:measurementsSet lido:sortorder="2">                <lido:measurementType lido:encodinganalog="dimension_type">width</lido:measurementType>                <lido:measurementUnit lido:encodinganalog="dimension_unit">centimeters</lido:measurementUnit>                <lido:measurementValue>89.5</lido:measurementValue>              </lido:measurementsSet>            </lido:objectMeasurements>          </lido:objectMeasurementsSet>        </lido:objectMeasurementsWrap>      </lido:objectIdentificationWrap>      <lido:eventWrap>        <lido:eventSet>          <lido:event>            <lido:eventType>              <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00012</lido:conceptID>              <lido:conceptID lido:type="URI">http://www.cidoc-crm.org/crm-concepts/E65</lido:conceptID>              <lido:term xml:lang="en">creation</lido:term>            </lido:eventType>            <lido:eventActor>              <lido:displayActorInRole>artist: Pierre Puvis de Chavannes, french (Lyon 1824 â€“ 1898 Paris)</lido:displayActorInRole>              <lido:actorInRole>                <lido:actor lido:type="person">                  <lido:actorID lido:source="SzÃ©pmÅ±vÃ©szeti MÃºzeum" lido:type="local">519</lido:actorID>                  <lido:actorID lido:source="VIAF" lido:type="URI">http://viaf.org/viaf/51724541</lido:actorID>                  <lido:nameActorSet>                    <lido:appellationValue lido:pref="preferred">Pierre Puvis de Chavannes</lido:appellationValue>                    <lido:sourceAppellation>SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:sourceAppellation>                  </lido:nameActorSet>                  <lido:nameActorSet>                    <lido:appellationValue lido:pref="alternate">Pierre Puvis de Chavannes</lido:appellationValue>                    <lido:sourceAppellation>SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:sourceAppellation>                  </lido:nameActorSet>                  <lido:nameActorSet>                    <lido:appellationValue lido:pref="alternate">Pierre CÃ©cile Puvis de Chavannes</lido:appellationValue>                    <lido:sourceAppellation>SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:sourceAppellation>                  </lido:nameActorSet>                  <lido:nationalityActor>                    <lido:term>french</lido:term>                  </lido:nationalityActor>                  <lido:vitalDatesActor>                    <lido:earliestDate>1824</lido:earliestDate>                    <lido:latestDate>1898</lido:latestDate>                  </lido:vitalDatesActor>                </lido:actor>                <lido:roleActor>                  <lido:term>artist</lido:term>                </lido:roleActor>              </lido:actorInRole>            </lido:eventActor>            <lido:eventDate>              <lido:displayDate>1897</lido:displayDate>              <lido:date>                <lido:earliestDate>1897</lido:earliestDate>                <lido:latestDate>1897</lido:latestDate>              </lido:date>            </lido:eventDate>            <lido:eventMaterialsTech>              <lido:displayMaterialsTech>oil on canvas</lido:displayMaterialsTech>            </lido:eventMaterialsTech>          </lido:event>        </lido:eventSet>      </lido:eventWrap>    </lido:descriptiveMetadata>    <lido:administrativeMetadata xml:lang="en">      <lido:rightsWorkWrap>        <lido:rightsWorkSet>          <lido:creditLine xml:lang="en">Copyright Â© SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:creditLine>        </lido:rightsWorkSet>      </lido:rightsWorkWrap>      <lido:recordWrap>        <lido:recordID lido:source="SzÃ©pmÅ±vÃ©szeti MÃºzeum" lido:type="local object id">440</lido:recordID>        <lido:recordType>          <lido:conceptID lido:type="URI">http://terminology.lido-schema.org/lido00141</lido:conceptID>          <lido:term xml:lang="en">item</lido:term>        </lido:recordType>        <lido:recordSource lido:type="institution">          <lido:legalBodyID lido:type="local">SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:legalBodyID>          <lido:legalBodyName>            <lido:appellationValue lido:pref="preferred" xml:lang="hu">SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:appellationValue>            <lido:appellationValue lido:pref="alternate" xml:lang="en">Museum of Fine Arts Budapest</lido:appellationValue>          </lido:legalBodyName>          <lido:legalBodyWeblink lido:formatResource="text/html" lido:label="homepage" xml:lang="en">http://www.szepmuveszeti.hu</lido:legalBodyWeblink>        </lido:recordSource>        <lido:recordSource lido:type="europeana:dataProvider">          <lido:legalBodyName>            <lido:appellationValue lido:pref="preferred" xml:lang="hu">SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:appellationValue>            <lido:appellationValue lido:pref="alternate" xml:lang="en">Museum of Fine Arts Budapest</lido:appellationValue>          </lido:legalBodyName>          <lido:legalBodyWeblink lido:formatResource="text/html" lido:label="homepage" xml:lang="en">http://www.szepmuveszeti.hu</lido:legalBodyWeblink>        </lido:recordSource>        <lido:recordRights>          <lido:rightsHolder>            <lido:legalBodyName>              <lido:appellationValue lido:pref="preferred" xml:lang="hu">SzÃ©pmÅ±vÃ©szeti MÃºzeum</lido:appellationValue>              <lido:appellationValue lido:pref="alternate" xml... [Body clipped after 10000 chars, total length is 12123]
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'one' in  class eu.aliada.rdfizer.pipeline.format.xml.OXPath threw exception java.lang.ClassCastException: java.lang.String cannot be cast to org.w3c.dom.NodeList at VM_global_library.vm[line 55, column 21]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:87)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:216)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:311)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:230)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.apache.velocity.Template.merge(Template.java:356)
	at org.apache.velocity.Template.merge(Template.java:260)
	at eu.aliada.rdfizer.pipeline.format.xml.SynchXmlDocumentTranslator.process(SynchXmlDocumentTranslator.java:140)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
	at org.apache.camel.processor.interceptor.TraceInterceptor.process(TraceInterceptor.java:163)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:291)
	at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:200)
	at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.w3c.dom.NodeList
	at eu.aliada.rdfizer.pipeline.format.xml.OXPath.one(OXPath.java:296)
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
	... 32 more

```

Have you tried to RDFize a LIDO record after doing last week´s changes?

**Comment by agazzarini** [comment]
Ok, that probably has to do with the new XPATH engine: Could you please 
fill a bug and send me the file you were trying to index?

Thx
Andrea

**Comment by idoiamurua** [comment]
Hi Andrea,

Here I send to you the “infraestruture.log” and the LIDO records file I imported.

Best,
Idoia

De: Andrea Gazzarini [mailto:notifications@github.com]
Enviado el: lunes, 11 de mayo de 2015 15:29
Para: ALIADA/aliada-tool
CC: Murua Belacortu, Idoia
Asunto: Re: [aliada-tool] RDFizer: LIDO bug (#106)

Ok, that probably has to do with the new XPATH engine: Could you please
fill a bug and send me the file you were trying to index?

Thx
Andrea

**Comment by agazzarini** [comment]
Most probably it is somthing that has been introduced with the new XPATH engine. I will check that tomorrow

**Comment by agazzarini** [comment]
Issue has been fixed. The cause was a minor bug on the XPATH evaluation in case the expression contains an attribute selector.
