### ISSUE TITLE
RDFizer: Add rdfs:label to provide a human-readable version of a resource's name

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#121]
The rdfs:label , as it explains in http://www.w3.org/TR/2004/REC-rdf-schema-20040210/#ch_label , may be used to provide a human-readable version of a resource's name.
 
The CIDOC-FRBRoo ontology we use inside ALIADA ontology is very complex and it does not attach “data properties” directly to these main entities. It always uses the “P1_is_identified by” object property (and its subproperties: P102_has_title, P131_is_identified_by, P149_is_identified_by, P48_has_preferred_identifier, P78_is_identified_by, P87_is_identified_by) to associate a name to an object, in the following way:
``` 
<M1>    <http://erlangen-crm.org/current/P102_has_title>      <T1> .
<T1>    <http://erlangen-crm.org/current/P3_has_note> "Quijote" .
```

It would be very helpful to add the rdfs:label to some resources, so that the end user can know at a first glance the reource´s title or name.
```
<M1>    <http://www.w3.org/1999/02/22-rdf-syntax-ns#label>    "Quijote".
```
This enhacement implies modifying the MARC BIB, MARC AUTH, LIDO and DC mapping files of the RDFizer, so that every time one of the following properties is attached to any resource: P1_is_identified by, P102_has_title, P131_is_identified_by, P149_is_identified_by, P48_has_preferred_identifier, P78_is_identified_by or P87_is_identified_by, the `<http://www.w3.org/2000/01/rdf-schema#label>` property must also be attached to the resource with the value that is associated to the `<http://erlangen-crm.org/current/P3_has_note>` property. That is, if now the following is generated:
 
```
<M1>    <http://erlangen-crm.org/current/P102_has_title>      <T1> .
<T1>    <http://erlangen-crm.org/current/P3_has_note> "Quijote" .
 ```
Then the following triple must also be added:
 ```
<M1>    <http://www.w3.org/2000/01/rdf-schema#label>      “Quijote” .
```

**Comment by agazzarini** [comment]
Problem is that actually we don't manage titles and other entities separately, so we have functions (actually macros) for building triples depending on several kinds of patterns. So the question is: is that ok if we put an rdfs:label beside each P3_has_note?

**Comment by idoiamurua** [comment]
Do you mean that if we have:

```
<M1>    <http://erlangen-crm.org/current/P102_has_title>      <T1> .
<T1>    <http://erlangen-crm.org/current/P3_has_note> "Quijote" .
 ```

you would add?

```
<M1>    <http://erlangen-crm.org/current/P102_has_title>      <T1> .
<T1>    <http://erlangen-crm.org/current/P3_has_note> "Quijote" .
<T1>    <http://www.w3.org/2000/01/rdf-schema#label>      “Quijote” .
``` 

What we need is:

```
<M1>    <http://erlangen-crm.org/current/P102_has_title>      <T1> .
<T1>    <http://erlangen-crm.org/current/P3_has_note> "Quijote" .
<M1>    <http://www.w3.org/2000/01/rdf-schema#label>      “Quijote” .
```

**Comment by agazzarini** [comment]
mmm...how can we generalize such behaviour? We can 

a) mapping by mapping decide where to put the rdfs:label...this is a *huge* work
b) decide to put such label only to (for example) titles and names (better)

What do you think?

**Comment by idoiamurua** [comment]
I think b) option is enough.
How can you distinguish that it is a title/name? By the MARC tag you are processing?

**Comment by agazzarini** [comment]
yes

**Comment by idoiamurua** [comment]
Hi Andrea,

I have just pulled the last versión of the RDFizer from Github and tried to compile it, but it has an error in the following file:

OXPath.java

Did you push the correct version to Github?

Best,
Idoia

De: Andrea Gazzarini [mailto:notifications@github.com]
Enviado el: jueves, 10 de septiembre de 2015 14:33
Para: ALIADA/aliada-tool
CC: Murua Belacortu, Idoia
Asunto: Re: [aliada-tool] RDFizer: Add rdfs:label to provide a human-readable version of a resource's name (#121)


Closed #121<https://github.com/ALIADA/aliada-tool/issues/121>.

**Comment by agazzarini** [comment]
I have no errors, that is really strange...could you please paste the stacktrace?

**Comment by idoiamurua** [comment]
The stacktrace that appears in "infraestructure.log" file is:

```
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'combine' in  class eu.aliada.rdfizer.pipeline.format.xml.OXPath threw exception java.lang.Error: Unresolved compilation problems:
        subfield cannot be resolved to a variable
        Syntax error on tokens, ( expected instead
        i cannot be resolved to a variable
        The type of the expression must be an array type but it resolved to int
        Syntax error on token ";", [ expected
        i cannot be resolved to a variable
        Syntax error, insert "]" to complete ArrayAccess
        Syntax error, insert ")" to complete Expression
        Syntax error, insert ")" to complete VariableInitializer
        i cannot be resolved to a variable
        Syntax error on token ")", ; expected
        i cannot be resolved to a variable
        i cannot be resolved to a variable
        subfield cannot be resolved
        Syntax error on tokens, Expression expected instead
        Syntax error on token ",", . expected
        Syntax error on token "-", -- expected
 at marcxml.frbr.n3.vm[line 86, column 18]
        at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:261)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
        at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
        at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
        at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
        at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
        at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)

```

I have generated the rdfizer WAR file in my Eclipse and uploaded to aliada.scanbit.net machine. The thing is that I have just realised that although Eclipse generates the WAR file giving no errors/warnings, I can see when I open `eu.aliada.rdfizer.pipeline.format.xml.OXPath.java` file, that it has an error in line 407 (combine() function), because of the line breaks inside "Arrays.stream" function.

**Comment by idoiamurua** [comment]
Eclipse shows the following errors:

[cid:image001.png@01D0EC8B.A6A9A790]

De: Andrea Gazzarini [mailto:notifications@github.com]
Enviado el: jueves, 10 de septiembre de 2015 16:14
Para: ALIADA/aliada-tool
CC: Murua Belacortu, Idoia
Asunto: Re: [aliada-tool] RDFizer: Add rdfs:label to provide a human-readable version of a resource's name (#121)


I have no errors, that is really strange...could you please paste the stacktrace?

**Comment by idoiamurua** [comment]
I don't have this problem: are you sure you're using Java8 (Windows --> 
Preferences --> Installed JRE) and that is set for that project? Could 
you please run Maven --> Update Project Conf?

**Comment by idoiamurua** [comment]
Yes. Now it is all OK. No errors and it works correctly in aliada.scanbit.net machine.
The JRE in Eclipse was OK (1.8) but the Java Compiler was configured with 1.7 version ...... I have just installed the plug-in of Eclipse to allow compiling with 1.8.
Thank you very much!!!

**Comment by agazzarini** [comment]
That's great! You're welcome ;)

**Comment by idoiamurua** [comment]
@agazzarini 

I have done the same for LIDO and DC (lido.n3.vm, VM_global_librray.vm and dc.n3.vm files modified in Github).
Could you do the same for MARC AUTH mapping?
I don´t dare to touch anything of MARC.

**Comment by agazzarini** [comment]
I did that

**Comment by idoiamurua** [comment]
I have just converted an AUTH record which you can access throug http://datos.artium.org/id/collections/library/auth/E21_Person/f8311587-f539-3b0d-82f4-e136a241cf42 and I do not see any rdfs:label.

The input MARC record used is:

```
<?xml version="1.0" encoding="UTF-8" ?>
<marc:collection xmlns:marc="http://www.loc.gov/MARC21/slim" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/MARC21/slim http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
	<marc:record>
		<marc:leader>02848cz  a2200541n  4500</marc:leader>
		<marc:controlfield tag="001">486845</marc:controlfield>
		<marc:controlfield tag="005">20130402080622.0</marc:controlfield>
		<marc:controlfield tag="008">781117n| azannaabn           b aaa      </marc:controlfield>
		<marc:datafield tag="010" ind1=" " ind2=" ">
			<marc:subfield code="a">n  78086005 </marc:subfield>
			<marc:subfield code="z">sh 85101935 </marc:subfield>
		</marc:datafield>
		<marc:datafield tag="035" ind1=" " ind2=" ">
			<marc:subfield code="a">(OCoLC)oca00221220</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="040" ind1=" " ind2=" ">
			<marc:subfield code="a">DLC</marc:subfield>
			<marc:subfield code="b">eng</marc:subfield>
			<marc:subfield code="e">rda</marc:subfield>
			<marc:subfield code="c">DLC</marc:subfield>
			<marc:subfield code="d">MdU</marc:subfield>
			<marc:subfield code="d">DLC-R</marc:subfield>
			<marc:subfield code="d">DLC</marc:subfield>
			<marc:subfield code="d">OCoLC</marc:subfield>
			<marc:subfield code="d">DLC</marc:subfield>
			<marc:subfield code="d">WU</marc:subfield>
			<marc:subfield code="d">OCoLC</marc:subfield>
			<marc:subfield code="d">DLC</marc:subfield>
			<marc:subfield code="d">DLC</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="046" ind1=" " ind2=" ">
			<marc:subfield code="f">18811025</marc:subfield>
			<marc:subfield code="g">19730408</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="053" ind1=" " ind2="0">
			<marc:subfield code="a">PQ2631.I37</marc:subfield>
			<marc:subfield code="c">French</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="053" ind1=" " ind2="0">
			<marc:subfield code="a">PQ6629.I23</marc:subfield>
			<marc:subfield code="c">Spanish</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="100" ind1="1" ind2=" ">
			<marc:subfield code="a">Picasso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="370" ind1=" " ind2=" ">
			<marc:subfield code="a">Málaga, Spain</marc:subfield>
			<marc:subfield code="b">Mougins, France</marc:subfield>
			<marc:subfield code="c">Spain</marc:subfield>
			<marc:subfield code="c">France</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="372" ind1=" " ind2=" ">
			<marc:subfield code="a">Cubism</marc:subfield>
			<marc:subfield code="2">lcsh</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="374" ind1=" " ind2=" ">
			<marc:subfield code="a">Artist</marc:subfield>
			<marc:subfield code="a">Painter</marc:subfield>
			<marc:subfield code="a">Sculptor</marc:subfield>
			<marc:subfield code="a">Printmaker</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="375" ind1=" " ind2=" ">
			<marc:subfield code="a">male</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Bīkāsū, Bāblū,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Luyisi Bikasuo, Babuluo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield></marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Luzi Bikasuo, Babuluo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Pikaso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Pikaso, Paburo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Pikasso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Ruiz, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Ruiz Picasso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Ruiz y Picasso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Ruys, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">Ruys Picasso, Pablo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">פיקאסו</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">פיקאסו, פאבלו,</marc:subfield>
			<marc:subfield code="d">1881־1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">פיקאסו, פבלו</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="1" ind2=" ">
			<marc:subfield code="a">ピカソパブロ,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="400" ind1="0" ind2=" ">
			<marc:subfield code="a">Bijiasuo,</marc:subfield>
			<marc:subfield code="d">1881-1973</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="667" ind1=" " ind2=" ">
			<marc:subfield code="a">Machine-derived non-Latin script reference project.</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="667" ind1=" " ind2=" ">
			<marc:subfield code="a">Non-Latin script references not evaluated.</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Picasso, von Maurice Raynal ... 1921.</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Pikaso reijishū, 1988:</marc:subfield>
			<marc:subfield code="b">p. 272 (Paburo Pikaso)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Bijiasuo hua feng, 1990:</marc:subfield>
			<marc:subfield code="b">t.p. (Bijiasuo)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Da Puvis de Chavannes a Matisse e Picasso, c2002:</marc:subfield>
			<marc:subfield code="b">t.p. (Picasso) p. 523 (Pablo Picasso, b. 1881 in Malaga [Spain]; d. 1973 in Mougins [France])</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Birželio naktys, 1973:</marc:subfield>
			<marc:subfield code="b">verso t.p. (Pablo Pikaso)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Picasso black and white, 2012</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Hui hua wan tong, 2010:</marc:subfield>
			<marc:subfield code="b">p. 2 (Pablo Picasso; Babuluo Luyisi Bikasuo)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Wikipedia, Feb. 26, 2013</marc:subfield>
			<marc:subfield code="b">(Pablo Ruiz y Picasso, known as Pablo Picasso; born 25 October 1881 in Málaga, Spain; died 8 April 1973 in Mougins, France; Spanish painter, sculptor, printmaker, ceramicist, and stage designer who spent most of his adult life in France. As one of the greatest and most influential artists of the 20th century, he is widely known for co-founding the Cubist movement, the invention of constructed sculpture, the co-invention of collage, and for the wide variety of styles that he helped develop and explore. Among his most famous works are the proto-Cubist Les Demoiselles d'Avignon (1907), and Guernica (1937), a portrayal of the German bombing of Guernica during the Spanish Civil War)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="670" ind1=" " ind2=" ">
			<marc:subfield code="a">Yu wang Bikasuo, 2012:</marc:subfield>
			<marc:subfield code="b">p. 15 (Pablo Ruiz Picasso; Babuluo Luzi Bikasuo)</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="952" ind1=" " ind2=" ">
			<marc:subfield code="a">RETRO</marc:subfield>
		</marc:datafield>
		<marc:datafield tag="953" ind1=" " ind2=" ">
			<marc:subfield code="a">xx00</marc:subfield>
			<marc:subfield code="b">rc15</marc:subfield>
		</marc:datafield>
	</marc:record>
</marc:collection>
```

**Comment by agazzarini** [comment]
Ok, I didn't do for authorities. Only for bib records. I'll do that
