### ISSUE TITLE
RDFizer: namespace input parameter contains all the object ID prefix

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#86]
@agazzarini  
We have changed the value of the "namespace" input parameter for the RDDFizer. Now it contains all the object URI prefix, and now the RDFizer only has to concatenate the class name and the object identification. That is, the namespace field in table `aliada`.`rdfizer_job_instances` may have the following values, e.g.:

http://aliada.scanbit.net:8891/id/
http://aliada.scanbit.net:8891/id/collections/
http://aliada.scanbit.net:8891/id/library/bib
http://aliada.scanbit.net:8891/id/collections/library/bib
...

The corresponding objects URIs would be:
http://aliada.scanbit.net:8891/id/F3_Manifestation_Product_Type/000000146458
http://aliada.scanbit.net:8891/id/collections/F3_Manifestation_Product_Type/000000146458
http://aliada.scanbit.net:8891/id/library/bib/F3_Manifestation_Product_Type/000000146458
http://aliada.scanbit.net:8891/id/collections/library/bib/F3_Manifestation_Product_Type/000000146458
......

Now the RDFizer does not need to add the "id/resource" string to the namespace input parameter.
I have been checking the RFizer code and I think that only the following code lines should be redone:

 * method LidoMainSubjectDetectionRule.computeFrom, line #46.
			final StringBuilder builder = new StringBuilder(configuration.getNamespace()).append("id/resource/");
 * VM_global_library.vm, line #8.
#macro (prefix)${configuration.namespace}id/resource#end

**Comment by idoiamurua** [comment]
@agazzarini @emiliano-cammilletti 
Is it enough to change the code lines I mentioned when I opened this issue?
If so, Will me, you or Emiliano change it?

**Comment by agazzarini** [comment]
The VM_Global_Library.vm should have something to do with the URI generation

I don't have time at the moment, I'm working in parallel on issue #76 
and #36 (https://github.com/ALIADA/aliada-tool/network)

**Comment by idoiamurua** [comment]
Yes. I mentioned a change in VM_Global_Library.vm and another ina a Java class. 
Specifically I mentioned:

* method LidoMainSubjectDetectionRule.computeFrom, line #46.
			final StringBuilder builder = new StringBuilder(configuration.getNamespace()).append("id/resource/");
 * VM_global_library.vm, line #8.
#macro (prefix)${configuration.namespace}id/resource#end

**Comment by agazzarini** [comment]
That should be enough

**Comment by idoiamurua** [comment]
OK. Any problem if I change that code?

**Comment by agazzarini** [comment]
No no, absolutely

**Comment by agazzarini** [comment]
@idoiamurua can we close this?

**Comment by idoiamurua** [comment]
I have not closed it yet because I wanted to test the changes I made for MARC in “eu.aliada.rdfizer.pipeline.format.lido.LidoMainSubjectDetectionRule.computeFrom()” method (LIDO changes in its mapping file are already tested). 
I tried to do so last Friday, but as I commented to you by e-mail when I generated the new WAR file of the RDFizer module, the following message appeared in the rdfizer.log file:


```
2015-03-06 09:33:06,638 INFO  <RDF-IZER-00001> : RDF-izer is starting...
2015-03-06 09:33:06,639 INFO  <RDF-IZER-00010> : RDF-izer open for e-business.
2015-03-06 09:33:09,699 INFO  <RDF-IZER-00011> : Shutdown procedure for RDF-izer has been initiated...
2015-03-06 09:33:09,700 ERROR <RDF-IZER-00042> : Management subsystem failure. See below for further details.
javax.management.InstanceNotFoundException: ALIADA:Module=RDFizer
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546)
        at eu.aliada.rdfizer.listeners.ApplicationLifecycleListener.contextDestroyed(ApplicationLifecycleListener.java:40)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5002)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5647)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1653)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2015-03-06 09:33:09,701 INFO  <RDF-IZER-00012> : RDF-izer has been shutdown.
```

Has anyone uploaded a new version of the RDFizer WAR to the webapps folder of Tomcat in aliada.scanbit.net?

**Comment by xmolero** [comment]
No, it is the same version that you leave it.

**Comment by idoiamurua** [comment]
The changes done in the RDFizer regarding the URI prefix have already been tested.
